In [52]:
import numpy as np

# 1. Create a vector with values ranging from 15 to 55 and print all values except the first and last.

In [53]:
arr = np.arange(15,56)
print(arr[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


# 2. Create a 3X4 array using np.full().

In [54]:
np.full((3,4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

# 3. Create a 3x3 matrix filled with values from 10 to 18. Use np.arange() and np.reshape().

In [55]:
np.arange(10,19).reshape(3,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# 4. Create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5 using np.diag().

In [56]:
np.zeros(25, int).reshape(5,5)

array = np.array([1, 2, 3, 4])
diag_matrix = np.diag(array)
diag_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# 5. Create a null vector of size 10 using np.zeros() and update sixth value to 11.

In [57]:
arr = np.zeros(10, int)
arr[5] = 11
arr

array([ 0,  0,  0,  0,  0, 11,  0,  0,  0,  0])

# 6. Convert an array to a float type using np.asfarray().

In [58]:
float_arr = np.asfarray(arr)
float_arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

# 7. Swap columns in a given array. Such as:

In [59]:
arr = np.arange(0,12).reshape(3,4)
print("Before swap:\n\n", arr)

arr[:, :] = arr[:, ::-1]
print("\nAfter swap:\n\n", arr)


Before swap:

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

After swap:

 [[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


# 8. Capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. Use np.char.capitalize(), np.char.lower(), np.char.upper(), np.char.swapcase(), np.char.title().

In [60]:
given_array = np.array(['hello', 'world', 'this', 'is', 'a', 'test'])

capitalized_array = np.char.capitalize(given_array)
lowercase_array = np.char.lower(given_array)
uppercase_array = np.char.upper(given_array)
swapcase_array = np.char.swapcase(given_array)
titlecase_array = np.char.title(given_array)

print("Original Array:", given_array)
print("Capitalized Array:", capitalized_array)
print("Lowercase Array:", lowercase_array)
print("Uppercase Array:", uppercase_array)
print("Swapcase Array:", swapcase_array)
print("Title-case Array:", titlecase_array)


Original Array: ['hello' 'world' 'this' 'is' 'a' 'test']
Capitalized Array: ['Hello' 'World' 'This' 'Is' 'A' 'Test']
Lowercase Array: ['hello' 'world' 'this' 'is' 'a' 'test']
Uppercase Array: ['HELLO' 'WORLD' 'THIS' 'IS' 'A' 'TEST']
Swapcase Array: ['HELLO' 'WORLD' 'THIS' 'IS' 'A' 'TEST']
Title-case Array: ['Hello' 'World' 'This' 'Is' 'A' 'Test']


# 9. Get the dates of yesterday, today and tomorrow using np.datetime64() and np.timedelta64().

In [61]:
today = np.datetime64('today')

yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-05-28
Today: 2024-05-29
Tomorrow: 2024-05-30


# 10.Append values to the end of an array using np.append(). Original array: [10, 20, 30] Expected Output: [10 20 30 40 50 60 70 80 90]

In [62]:
arr = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60, 70, 80, 90])

arr = np.append(arr, arr2)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])